### ISSUE TITLE
Feature request: support of multiple types of text inputs

### ISSUE THREAD

**Issue by emdzsi** [Alterplay/APValidators#3]
Hi,

I don't know you guys are planning this but it would be nice, if not only UIKit text inputs can be validated but other custom types. For example I'm using Material Control For iOS's MDTextField, unfortunately it's a UIControl only.

**Comment by hawk-ukr** [comment]
Hello,

Thank you for your suggestions.

APValidators hardly counts on internals of UITextField and UITextView. Pure UIControl has nothing to validate but subclasses have. So we cannot provide support for every subclass because there are plenty of them on github. 

You can still use APValidators from code but without intergration with Interface Builder in Xcode. Or you can create analog of our category to support MDTextField - https://github.com/Alterplay/APValidators/blob/master/Pod/Classes/Categories/UITextField%2BAPValidators.m Please feel free to contribute it to our codebase and we will add it as additional feature. 

Best regards
